[project]
name = 'Grid-Optimization-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.energy-transfer-agreement]
path = 'contracts/energy-transfer-agreement.clar'
clarity_version = 2
epoch = 2.5

[contracts.power-plant-management]
path = 'contracts/power-plant-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
